services:
  app:
    container_name: eduplan
    image: eduplan-back
    build: ./
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://postgresqldb:5432/eduplan
      db-user: postgres
      db-password: postgres
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eduplan